### ISSUE TITLE
Add methods to dag.Info :)

### ISSUE THREAD

**Issue by ramfox** [qri-io/dag#6]
Proposal:

1) rename Info.Paths to Info.Labels
2) `func (i *Info) Size() int` => returns the size of the whole DAG
3) `func (i *Info) SubDAGSize(val interface{}) int` 
      - -1 means error
      - switch on interface
      - if it's an int, assume its the index of the hash, return the size of the subdag at that index
      - if it's a string, check to see if it is a label, if so get the size of the subdag at that label
      - if it's a string but not a label, assume its a hash, attempt to get the size of the subdag at that hash
      - if it's not int or string, return -1

  OR

  `func (i *Info) SubDAGSizeByHash(hash string) int`
  `func (i *Info) SubDAGSizeByIndex(index int) int`
  `func (i *Info) SubDAGSizeByLabel(label string) int`

4) `func (i *Info) AddLabel(label, hash string) error`
    - makes sure the hash exists in the Manifest
    - if not, error
    - otherwise, add a label with that index of that hash to the Info.Labels

**Comment by dustmop** [comment]
I would prefer the three separate methods for `SubDAGSize...`, but they should return (int, error) instead of using -1 as an error value.

**Comment by b5** [comment]
> 1. rename info.Paths to info.Labels

let's do it, and be sure to update all comments accordingly

2. Big fan. Let's have `Size()` return an `int64`. It'll match the [os.FileInfo](https://golang.org/pkg/os/#FileInfo) interface.

3.  I think we should instead consider making DagInfo a "recursive structure" that returns nil if non-existent

```go
func (i *Info) InfoAtHash(hash string) *Info {}

func (i *Info) InfoAtIndex(idx int) *Info {}

func (i *Info) InfoAtLabel(label string) *Info {}

// eg usage: print all label sizes for a dag.Info di, which you got from somewhere else
var di *dag.Info

for label := range di.Labels {
 if info := di.InfoAtLabel(label); info != nil {
    fmt.Println(info.Size())
 }
}
```

4. Love the `AddLabel` func. Let's do it.

**Comment by b5** [comment]
Also, we need to settle the debate between `hash/CID` or just calling it `id` at the dag package level. IMHO this should just be `ID`. `CID` is a protocol labs term-of-art, and the dag package long term is going to need to play well in a few different DAG environments (git, dat)

**Comment by ramfox** [comment]
Also adding:

```golang
// IDIndex returns the node index of an id 
func (m *Manifest) IDIndex(id string) (int, error)

// And as per convo btw me and @b5, also adding:
// SubDAG returns a Manifest of a DAG at a specific hash in an already existing Manifest
func SubDAG(m *Manifest, id string) *Manifest
```
